# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-31 02:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.IntegerField(choices=[(0, 'less than 1 month'), (1, '1-3 months'), (2, '3-6 months'), (3, '6-12 months'), (4, '12-24 months'), (5, '2-5 years')], default=0, verbose_name='Age Group')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(default='', max_length=150, verbose_name='Symptom Name')),
                ('description', redactor.fields.RedactorField(default='', verbose_name='Description/Summary')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('childName', models.CharField(default='noNameProvided', max_length=150)),
                ('dob', models.DateField(default=datetime.datetime.now)),
                ('activate', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('headingId', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(default='', max_length=500, verbose_name='Heading Title')),
                ('categoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iPoorly.Category', verbose_name='Symptom')),
            ],
        ),
        migrations.CreateModel(
            name='SubHeading',
            fields=[
                ('subHeadingId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=150, verbose_name='Title')),
                ('text', redactor.fields.RedactorField(verbose_name='Content')),
                ('lastEdited', models.DateTimeField(auto_now=True)),
                ('ageGroup', models.ManyToManyField(to='iPoorly.AgeGroup')),
                ('headingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iPoorly.Heading', verbose_name='Heading')),
            ],
        ),
    ]
