# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-01 22:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iPoorly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryLog',
            fields=[
                ('diary_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('text', redactor.fields.RedactorField(verbose_name='Diary Entry')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
