# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-01 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iPoorly', '0002_diarylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarylog',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iPoorly.Child'),
        ),
    ]
