# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-10 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iPoorly', '0004_auto_20180102_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ['-dob']},
        ),
        migrations.AlterModelOptions(
            name='diarylog',
            options={'ordering': ['created_on']},
        ),
        migrations.AddField(
            model_name='diarylog',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='diarylog',
            name='title',
            field=models.CharField(default='', max_length=150, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='diarylog',
            name='text',
            field=models.TextField(default='', max_length=2400, verbose_name='Log content'),
        ),
    ]
